-- Ejecutar en el SQL Editor de Supabase para crear las tablas

-- Tabla categorias
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL
);

-- Tabla gastos
CREATE TABLE IF NOT EXISTS gastos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monto NUMERIC NOT NULL,
  fecha DATE NOT NULL,
  descripcion TEXT,
  categoria_id BIGINT NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT
);

-- Índice para consultas por fecha
CREATE INDEX IF NOT EXISTS idx_gastos_fecha ON gastos(fecha DESC);
CREATE INDEX IF NOT EXISTS idx_gastos_categoria_id ON gastos(categoria_id);

-- Habilitar RLS (opcional): si usas Row Level Security, añade políticas para permitir acceso.
-- Por defecto con anon key podrás leer/escribir si en Supabase está permitido para la anon key.
